### PR TITLE
Story/finish up modules

### PR DESCRIPTION
**Pull request by MarcD-Developer**
Adding touches to modules.  Awaiting data from soap and rest so that I may continue working on the modules to work a bit better.

### CODE REVIEW

**Comment by erchiggins** [comment]
So... we're waiting?

**Comment by MarcD-Developer** [comment]
@erchiggins I can't grab any data as far as I know from the rest service.

**Comment by erchiggins** [comment]
@SmokedEel Phil just fixed an issue in the Housing SOAP service that might help.
Should be part of master now.

**Comment by erchiggins** [comment]
I do still need to find out from Brandon whether his is ready to merge, so you may not be able to access the Logic functionality yet.

**Comment by MarcD-Developer** [comment]
@erchiggins I tried accessing the information just now, I'm still unable to access it at the moment.

**Comment by MarcD-Developer** [comment]
@erchiggins I've just finished looking over this pull request, it should be good to go!

**Review by erchiggins — APPROVED** [review]

**Pull request merged**
